# Generated by Django 3.2.8 on 2021-11-15 14:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('sno_category', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cat_pics/', verbose_name='Cover Photo')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug Field')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno_post', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date of Posting')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_pics/', verbose_name='Cover Photo')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug Field')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('sno_comment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BlogApp.post')),
            ],
        ),
    ]
