# Generated by Django 3.2.8 on 2021-11-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Posting'),
        ),
    ]
