# Generated by Django 3.2.8 on 2021-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_postcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Author Description'),
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='author_pics', verbose_name='Author Cover'),
        ),
    ]
