# Generated by Django 4.2.3 on 2023-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
