# Generated by Django 4.2.3 on 2024-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField()),
                ('stream', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
    ]
